apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: mysqldb-container
          image: mysql
          env:
            - name: MYSQL_USER
              value: "oumayma"
            - name: MYSQL_PASSWORD
              value: "oumayma"
            - name: MYSQL_ROOT_PASSWORD
              value: "oumayma"
            - name: MYSQL_DATABASE
              value: "pet_store"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}