version: '3'

services:
  mysqldb-container:
    image: mysql
    container_name: "mysqldb-container"
    environment:
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - /var/lib/docker/volumes/springboot-mysql-devops-pipeline-volume/_data:/var/lib/mysql

  pet-store-app-container:
    build:
      context: ~/Documents/DevOps/DevOps_TP_2_Pipeline/
      dockerfile: Dockerfile
    image: pet-store-app:latest
    container_name: "pet-store-app-container"
    restart: on-failure
    depends_on:
      - mysqldb-container
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - DATABASE_HOST=mysqldb-container
      - DATABASE_USER=${MYSQLDB_USER}
      - DATABASE_PASSWORD=${MYSQLDB_PASSWORD}
      - DATABASE_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DATABASE_NAME=${MYSQLDB_DATABASE}
      - DATABASE_PORT=${MYSQLDB_DOCKER_PORT}

networks:
  default:
    external:
      name: pet-store-network